# fly.toml file generated for flights-delay on 2023-10-08T15:04:51-03:00

app = "flights-delay"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "eze"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
